[package]
name = "chip8-sdl"
version = "0.1.0"
authors = ["Daniele D'Orazio <d.dorazio96@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.7"
structopt = "0.3"
sdl2 = { version = "0.34", features = ["bundled"] }

chip8 = { path = "../chip8" }
